# Backchannel Configuration for Role-Based Interviews
# Short responses for real-time interview feedback

version: "0.1"

roles:
  ba_anti_fraud:
    name: "Бизнес-аналитик (антифрод)"
    
    # Positive responses (good answers)
    positive:
      - "Понял кейс, уточните метрику FPR/TPR."
      - "Хорошо, расскажите про оптимизацию правил."
      - "Понятно, какие были результаты в цифрах?"
      - "Отлично, как работали с ложноположительными?"
      - "Понял, уточните процесс постановки требований."
      - "Хорошо, как взаимодействовали с заказчиками?"
      - "Понятно, какие тест-кейсы разрабатывали?"
      - "Отлично, расскажите про работу с платежными системами."
    
    # Neutral responses (unclear answers)
    neutral:
      - "Уточните, пожалуйста, детали."
      - "Понял, но нужны конкретные примеры."
      - "Хорошо, но расскажите подробнее."
      - "Понятно, какие были метрики?"
      - "Уточните, как именно это работало?"
      - "Понял, но нужны цифры и результаты."
      - "Хорошо, но какие были сложности?"
      - "Понятно, как измеряли эффективность?"
    
    # Negative responses (poor answers)
    negative:
      - "Понял, но это не совсем то, что нужно."
      - "Уточните, есть ли опыт с антифрод-системами?"
      - "Понятно, но нужен более конкретный опыт."
      - "Хорошо, но расскажите про реальные кейсы."
      - "Понял, но какие были результаты?"
      - "Уточните, работали ли с метриками качества?"
      - "Понятно, но нужен опыт с правилами."
      - "Хорошо, но какие инструменты использовали?"
    
    # Follow-up prompts
    followup:
      - "Расскажите подробнее."
      - "Какие были результаты?"
      - "Как это работало на практике?"
      - "Какие метрики использовали?"
      - "Какие были сложности?"
      - "Как измеряли эффективность?"
      - "Приведите конкретный пример."
      - "Какие инструменты применяли?"

  it_dc_ops:
    name: "Ведущий специалист ИТ (ЦОД)"
    
    # Positive responses (good answers)
    positive:
      - "Принято. Уточните конфигурацию RAID и BMC."
      - "Понял, расскажите про настройку сетей."
      - "Хорошо, какие были параметры BIOS?"
      - "Отлично, как работали с инцидентами?"
      - "Понятно, уточните процесс монтажа СКС."
      - "Хорошо, как настраивали Active Directory?"
      - "Понял, какие инструменты использовали?"
      - "Отлично, расскажите про мониторинг."
    
    # Neutral responses (unclear answers)
    neutral:
      - "Уточните, пожалуйста, технические детали."
      - "Понял, но нужны конкретные параметры."
      - "Хорошо, но расскажите про настройки."
      - "Понятно, какие были конфигурации?"
      - "Уточните, как именно это настраивалось?"
      - "Понял, но нужны технические подробности."
      - "Хорошо, но какие были сложности?"
      - "Понятно, как решали проблемы?"
    
    # Negative responses (poor answers)
    negative:
      - "Понял, но это не совсем техническая задача."
      - "Уточните, есть ли опыт с серверным оборудованием?"
      - "Понятно, но нужен более технический опыт."
      - "Хорошо, но расскажите про реальные настройки."
      - "Понял, но какие были параметры?"
      - "Уточните, работали ли с BIOS/BMC?"
      - "Понятно, но нужен опыт с RAID."
      - "Хорошо, но какие инструменты использовали?"
    
    # Follow-up prompts
    followup:
      - "Расскажите про технические детали."
      - "Какие были параметры настройки?"
      - "Как это настраивалось?"
      - "Какие конфигурации использовали?"
      - "Какие были сложности?"
      - "Как решали технические проблемы?"
      - "Приведите конкретный пример настройки."
      - "Какие инструменты применяли?"

# Common responses (used for both roles)
common:
  # Generic positive
  generic_positive:
    - "Понял."
    - "Хорошо."
    - "Отлично."
    - "Понятно."
    - "Принято."
  
  # Generic neutral
  generic_neutral:
    - "Уточните, пожалуйста."
    - "Расскажите подробнее."
    - "Нужны детали."
    - "Понял, но нужны примеры."
    - "Хорошо, но расскажите больше."
  
  # Generic negative
  generic_negative:
    - "Понял, но это не то."
    - "Нужен другой опыт."
    - "Не совсем подходит."
    - "Уточните, есть ли другой опыт?"
    - "Понятно, но нужны другие навыки."
  
  # Transition phrases
  transition:
    - "Переходим к следующему вопросу."
    - "Теперь другой вопрос."
    - "Следующий блок."
    - "Переходим дальше."
    - "Следующий вопрос."

# Response selection logic
selection:
  # Score thresholds for response type selection
  positive_threshold: 0.7
  negative_threshold: 0.3
  
  # Confidence thresholds
  high_confidence_threshold: 0.8
  low_confidence_threshold: 0.4
  
  # Response length preferences
  max_response_length: 50  # characters
  prefer_short: true
